---

- hosts: docker_swarm
  gather_facts: yes
  become: yes

  tasks:
    - name: Import role robertdebock.update
      ansible.builtin.import_role:
        name: robertdebock.update
      tags:
        - role::update

    # - name: Import role devsec.hardening.os_hardening
    #   ansible.builtin.import_role:
    #     name: devsec.hardening.os_hardening
    #   tags:
    #     - role::os_hardening

    - name: Import role robertdebock.epel
      ansible.builtin.import_role:
        name: robertdebock.epel
      tags:
        - role::epel

    - name: Import role robertdebock.python_pip
      ansible.builtin.import_role:
        name: robertdebock.python_pip
      tags:
        - role::python_pip

    - name: Import role robertdebock.storage
      ansible.builtin.import_role:
        name: robertdebock.storage
      tags:
        - role::storage

    - name: Import role atosatto.docker-swarm
      ansible.builtin.import_role:
        name: atosatto.docker-swarm
      tags:
        - role::docker-swarm

    - name: Ensure docker daemon startup as a service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      tags:
        - role::docker-swarm


- hosts: docker_swarm_manager
  gather_facts: yes
  become: yes

  tasks:
    - name: Import role docker_tls
      ansible.builtin.import_role:
        name: docker_tls
      tags:
        - role::docker_tls
