---

- hosts: swarm
  # connection: local
  gather_facts: yes

  tasks:
    - name: Print some debug information
      vars:
          # Module Variables ("vars"):
          # --------------------------------
          # {{ vars | to_nice_yaml }}

        msg: |
          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_yaml }}

          GROUP NAMES Variables ("group_names"):
          --------------------------------
          {{ group_names | to_nice_yaml }}

          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_yaml }}

          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_yaml }}

      ansible.builtin.debug:
        msg: "{{ msg }}"
      run_once: yes
