---

collections:
  - name: amazon.aws
    version: 3.2.0
  - name: ansible.netcommon
    version: 2.6.1
  - name: community.aws
    version: 3.2.1
  - name: community.general
    version: 4.8.1
  - name: community.crypto
    version: 2.3.1
  - name: devsec.hardening
    version: 7.14.1

roles:
  # - name: atosatto.docker-swarm
  #   version: v2.3.0
  - name: atosatto.docker-swarm
    src: https://github.com/pandvan/ansible-dockerswarm
    version: master
  - name: robertdebock.epel
    version: 3.1.5
  - name: robertdebock.python_pip
    version: 4.3.0
  # - name: robertdebock.storage
  #   version: 5.1.1
  - name: robertdebock.storage
    src: https://github.com/pandvan/ansible-role-storage
    version: master
  - name: robertdebock.update
    version: 3.1.2
