---

collections:
  - name: amazon.aws
    version: 3.2.0
  - name: community.aws
    version: 3.2.1
  - name: community.general
    version: 4.8.1
  - name: community.crypto
    version: 2.3.1

roles:
  - name: nickjj.docker
    version: v2.1.0
  - name: robertdebock.bootstrap
    version: 6.0.3
  - name: robertdebock.buildtools
    version: 3.1.8
  - name: robertdebock.core_dependencies
    version: 2.1.9
  - name: robertdebock.docker_ce
    version: 3.3.0
  - name: robertdebock.epel
    version: 3.1.5
  - name: robertdebock.python_pip
    version: 4.3.0
  - name: robertdebock.update
    version: 3.1.2
