---

all:
  children:
    docker_swarm:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: "{{ playbook_dir }}/.ssh/kirahire.pem"

      hosts:
        kirahire-01:
          ec2_vm_name: kirahire-01
        kirahire-02:
          ec2_vm_name: kirahire-02

    docker_swarm_manager:
      hosts:
        kirahire-01: ~
    docker_swarm_worker:
      hosts:
        kirahire-02: ~
