---

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Get repo list
      command: yum repolist enabled
      changed_when: false
      register: yum_repolist

    - name: Check if EPEL repository has been addes
      assert:
        that:
          - "'epel' in yum_repolist.stdout"
